accelerator: ddp
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 16
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
clip_grad: 1.0
concept_store: data/concept_store.pt
dataset_basedir: data
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
flush_logs_every_n_steps: null
gamma: 0.01
gpus: 0
gradient_clip_algorithm: null
gradient_clip_val: null
h_dim: 768
ipus: null
kqv_dim: 256
lamda: 0.01
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 2.0e-05
max_epochs: 5
max_steps: -1
max_time: null
min_epochs: null
min_lr: 0
min_steps: null
model_name: xlnet-base-cased
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_heads: 1
name: temp
nokeyword: false
nolil: false
notopic: false
num_classes: 2
num_gpus: 1
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
topk: 100
tpu_cores: null
track_grad_norm: -1
use_weight: false
val_check_interval: 1.0
warmup_prop: 0.01
weight_decay: 0.01
weights_save_path: null
weights_summary: top
